#!/usr/bin/env python
import sys, os

num_nodes = sys.argv[1]
batch_size = 128 // int(num_nodes)
model = sys.argv[2]
epoch = int(sys.argv[3])
options = sys.argv[4]

cmd = 'python ./multiproc.py --master_port 29501 --nproc_per_node {num_nodes} ./main.py --dataset cifar10 --arch {model} --resume results/{model}/checkpoint-{epochs}.pth.tar --epochs {epochs_plus_one} --evaluate --raport-file test_raport.json --workspace results/{model} --batch-size {batch_size} --label-smoothing 0 --weight-decay 1e-4 {options} ~/data/cifar10'.format(
        num_nodes=num_nodes, batch_size=batch_size, model=model, epochs=epoch, epochs_plus_one=epoch+1, options=options)

print(cmd)
os.system(cmd)

cmd = 'python compute_std.py results/{} {}'.format(model, num_nodes)
print(cmd)
os.system(cmd)
